[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]

size = 14
normal = { family = "Jetbrains Mono Nerd Font", style = "Regular" }

[window]
padding = {x = 10, y = 10}

[terminal]
shell = {program = "/usr/bin/fish"}
